# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIfzhXVQWGikIzphlk4T9qH6xurn2UsQ
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import io

# ============================================================================
# CONFIGURATION
# ============================================================================
st.set_page_config(
    page_title="Skin Lesion Classifier",
    page_icon="🔬",
    layout="centered"
)

# ============================================================================
# LOAD MODEL
# ============================================================================
@st.cache_resource
def load_model():
    """Load the trained model"""
    try:
        model = tf.keras.models.load_model("skin_cancer_model.h5")
        return model
    except Exception as e:
        st.error(f"Error loading model: {e}")
        return None

# ============================================================================
# CLASS MAPPINGS
# ============================================================================
# Original model classes (7)
original_classes = ['akiec', 'bcc', 'bkl', 'df', 'nv', 'vasc', 'mel']

# Target classes (10)
target_classes = [
    'Basal Cell Carcinoma',
    'Squamous Cell Carcinoma',
    'Actinic Keratosis',
    'Dermatofibroma',
    'Folliculitis',
    'Pyogenic Granuloma',
    'Seborrheic Keratosis',
    'Eczema',
    'Psoriasis',
    'Melanocytic Nevus'
]

# Mapping from 7 model outputs to 10 target classes
original_to_target = {
    'bcc': 'Basal Cell Carcinoma',
    'akiec': 'Actinic Keratosis',
    'df': 'Dermatofibroma',
    'bkl': 'Seborrheic Keratosis',
    'nv': 'Melanocytic Nevus',
    'mel': 'Melanocytic Nevus',  # Melanoma grouped with nevus for this demo
    'vasc': 'Pyogenic Granuloma'  # Vascular lesions mapped to pyogenic granuloma
}

# Class descriptions for user education
class_info = {
    'Basal Cell Carcinoma': 'Most common skin cancer. Slow-growing, rarely spreads.',
    'Squamous Cell Carcinoma': 'Second most common skin cancer. Can spread if untreated.',
    'Actinic Keratosis': 'Pre-cancerous rough, scaly patches from sun damage.',
    'Dermatofibroma': 'Benign fibrous skin nodule, usually on legs.',
    'Folliculitis': 'Inflammation of hair follicles, often from infection.',
    'Pyogenic Granuloma': 'Benign vascular growth, often after minor injury.',
    'Seborrheic Keratosis': 'Benign warty growth, common with aging.',
    'Eczema': 'Inflammatory skin condition causing itchy, red patches.',
    'Psoriasis': 'Autoimmune condition causing thick, scaly plaques.',
    'Melanocytic Nevus': 'Common mole, usually benign.'
}

# Risk levels
risk_levels = {
    'Basal Cell Carcinoma': ('Malignant', '#ff6b6b'),
    'Squamous Cell Carcinoma': ('Malignant', '#ff6b6b'),
    'Actinic Keratosis': ('Pre-malignant', '#ffd93d'),
    'Dermatofibroma': ('Benign', '#6bcf7f'),
    'Folliculitis': ('Benign', '#6bcf7f'),
    'Pyogenic Granuloma': ('Benign', '#6bcf7f'),
    'Seborrheic Keratosis': ('Benign', '#6bcf7f'),
    'Eczema': ('Benign', '#6bcf7f'),
    'Psoriasis': ('Benign', '#6bcf7f'),
    'Melanocytic Nevus': ('Benign', '#6bcf7f')
}

# ============================================================================
# PREPROCESSING
# ============================================================================
def preprocess_image(image):
    """Preprocess image for model prediction"""
    # Convert to RGB if needed
    if image.mode != 'RGB':
        image = image.convert('RGB')

    # Resize to model input size
    image = image.resize((224, 224))

    # Convert to array and normalize
    img_array = tf.keras.preprocessing.image.img_to_array(image)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0

    return img_array

# ============================================================================
# PREDICTION
# ============================================================================
def predict(image, model):
    """Make prediction on image"""
    # Preprocess
    processed_image = preprocess_image(image)

    # Predict
    predictions = model.predict(processed_image, verbose=0)[0]

    # Get original class probabilities
    original_probs = {cls: float(prob) for cls, prob in zip(original_classes, predictions)}

    # Map to target classes (aggregate probabilities)
    target_probs = {cls: 0.0 for cls in target_classes}

    for orig_cls, prob in original_probs.items():
        target_cls = original_to_target.get(orig_cls)
        if target_cls:
            target_probs[target_cls] += prob

    # Get top prediction
    top_class = max(target_probs, key=target_probs.get)
    top_prob = target_probs[top_class]

    return {
        'predicted_class': top_class,
        'confidence': top_prob,
        'risk_level': risk_levels[top_class][0],
        'risk_color': risk_levels[top_class][1],
        'description': class_info[top_class],
        'all_probabilities': target_probs
    }

# ============================================================================
# UI COMPONENTS
# ============================================================================
def display_results(result):
    """Display prediction results"""
    st.markdown("---")
    st.markdown("## 📊 Results")

    # Main prediction card
    col1, col2 = st.columns([2, 1])

    with col1:
        st.markdown(f"### {result['predicted_class']}")
        st.markdown(f"*{result['description']}*")

    with col2:
        risk_level = result['risk_level']
        risk_color = result['risk_color']
        st.markdown(f"""
        <div style="
            background-color: {risk_color};
            padding: 15px;
            border-radius: 10px;
            text-align: center;
            color: white;
            font-weight: bold;
            font-size: 20px;
        ">
            {risk_level}
        </div>
        """, unsafe_allow_html=True)

    # Confidence gauge
    st.markdown("### Confidence")
    confidence = result['confidence']
    st.progress(confidence)
    st.markdown(f"**{confidence*100:.1f}%**")

    # All probabilities
    st.markdown("### All Class Probabilities")

    sorted_probs = sorted(result['all_probabilities'].items(), key=lambda x: x[1], reverse=True)

    for cls, prob in sorted_probs[:5]:  # Show top 5
        col1, col2 = st.columns([3, 1])
        with col1:
            st.markdown(f"**{cls}**")
        with col2:
            st.markdown(f"{prob*100:.1f}%")
        st.progress(prob)

def display_disclaimer():
    """Display medical disclaimer"""
    st.markdown("---")
    st.markdown("""
    ### ⚠️ Medical Disclaimer

    This tool is for **educational and research purposes only**. It is NOT a substitute for professional medical advice, diagnosis, or treatment.

    **Always consult a qualified dermatologist or healthcare provider** for any skin concerns.

    The AI model has limitations:
    - Trained on limited datasets
    - May not generalize to all skin types
    - Cannot replace clinical examination
    """)

# ============================================================================
# MAIN APP
# ============================================================================
def main():
    st.title("🔬 Skin Lesion Classifier")
    st.markdown("Upload a skin lesion image for AI-powered analysis (10-class classification)")

    # Load model
    with st.spinner("Loading model..."):
        model = load_model()

    if model is None:
        st.error("Failed to load model. Please check the model file.")
        st.stop()

    st.success("✅ Model loaded successfully!")

    # Sidebar
    with st.sidebar:
        st.markdown("## 📋 About")
        st.markdown("""
        This app uses a deep learning model to classify skin lesions into 10 categories.

        **Classes detected:**
        - Basal Cell Carcinoma
        - Squamous Cell Carcinoma
        - Actinic Keratosis
        - Dermatofibroma
        - Folliculitis
        - Pyogenic Granuloma
        - Seborrheic Keratosis
        - Eczema
        - Psoriasis
        - Melanocytic Nevus
        """)

        st.markdown("## 📤 Upload Guidelines")
        st.markdown("""
        For best results:
        - Good lighting
        - In focus
        - Centered on lesion
        - No obstructions
        """)

    # File uploader
    uploaded_file = st.file_uploader(
        "Choose a skin lesion image...",
        type=['jpg', 'jpeg', 'png'],
        help="Upload a clear image of the skin lesion"
    )

    if uploaded_file is not None:
        # Display image
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            image = Image.open(uploaded_file)
            st.image(image, caption='Uploaded Image', use_container_width=True)

        # Predict button
        if st.button("🔍 Analyze Image", type="primary", use_container_width=True):
            with st.spinner("Analyzing image..."):
                try:
                    result = predict(image, model)
                    display_results(result)
                except Exception as e:
                    st.error(f"Error during prediction: {e}")

    # Always show disclaimer
    display_disclaimer()

if __name__ == "__main__":
    main()